### ISSUE TITLE
update video structure to be the same as akka

### ISSUE THREAD

**Issue by jessica-christie** [SYNQfm/SYNQ-Golang#118]

**Comment by jessica-christie** [comment]
@JHUShanZhong I've tested the sdk and the video/asset structure in the sdk supports everything that is in akka. It's probably the service that inserts the data into algolia that needs to be updated. Which service is that so I can move this issue?

**Comment by jessica-christie** [comment]
@JHUShanZhong I checked a couple of videos in akka vs serpent/algolia and they look like they have the same data. What exactly is the issue and can you provide examples?

**Comment by jessica-christie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [General : Investigate Video structure issue](https://trello.com/c/sQ60xAPe/908-general-investigate-video-structure-issue)

**Comment by JHUShanZhong** [comment]
@jessica-christie The video and asset structure seems to be up to date. I know that the account setting Fiona added to Akka has not been added to the SDK yet.

**Comment by jessica-christie** [comment]
@JHUShanZhong I'll close this and create another issue for that.
