### ISSUE TITLE
command upload_info does not check for video_id argument

### ISSUE THREAD

**Issue by martinatsynqfm** [SYNQfm/SYNQ-Golang#17]
if the `upload_info` command is run without any `video_id` argument, there is no error reported about the missing argument, but there is an error later when the program attempts to `v1/video/upload` with an empty string as `video_id`:
```
~/synq/SYNQ-Golang/cli $ go build && ./cli -api_key "${SYNQ_API_KEY}" -command upload_info
2017/06/23 17:05:44 Getting upload info for 
2017/06/23 17:05:44 Received {http://docs.synq.fm/api/v1/errors/invalid_uuid invalid_uuid Invalid uuid. Example: '1c0e3ea4529011e6991554a050defa20'.}
2017/06/23 17:05:44 Error : Invalid uuid. Example: '1c0e3ea4529011e6991554a050defa20'.
~/synq/SYNQ-Golang/cli $
```

***

a migitation for this may be to check whether `video_id` was supplied in the `case "upload_info"` section of `switch cmd`

**Comment by jessica-christie** [comment]
closing v1 issues...
