### ISSUE TITLE
cli: why os.Exit(-1) in response to errors?

### ISSUE THREAD

**Issue by martinatsynqfm** [SYNQfm/SYNQ-Golang#18]
the `cli` program calls `os.Exit(-1)` when it encounters errors

on my machine (bash and linux), bash reports the exit code as `255` which [traditionally](http://tldp.org/LDP/abs/html/exitcodes.html) is used to indicate that an exit code is out of range

**Comment by batmany13** [comment]
no specific reason, just habit on using these type of errors codes.  Happy to change this to whatever is needed, moving out of help wanted
