### ISSUE TITLE
response bodies are not closed

### ISSUE THREAD

**Issue by martinatsynqfm** [SYNQfm/SYNQ-Golang#22]
in `synq/api.go`, i don't think the bodies of the http responses are ever closed

> Clients must call resp.Body.Close when finished reading resp.Body.
https://golang.org/pkg/net/http/#ReadResponse

i may have misread the code, and the bodies may be closed somehow. i haven't made any tests

***

a fix for this may be to `defer resp.Body.Close()` at the beginning of the functions `parseAwsResp` and `parseSynqResp`

**Comment by jessica-christie** [comment]
closing v1 issues...
