### ISSUE TITLE
improve test coverage for multipartUpload()

### ISSUE THREAD

**Issue by batmany13** [SYNQfm/SYNQ-Golang#24]
Additional coverage for multipartUpload function

### multipartUpload

- [ ] multipartUpload: mock s3 service
- [ ] multipartUpload: successful upload to mock s3 service
- [ ] multipartUpload: failure to get bucketOfUploadAction
- [ ] multipartUpload: failure to get regionOfUploadAction
- [ ] multipartUpload: failure to get tokenOfUploaderURL
- [ ] multipartUpload: failure to create NewSession

original in #12

**Comment by JulianNymark** [comment]
this is also not specific to the `importer service` Epic, so unlinking.

This is more SDK centric.

**Comment by jessica-christie** [comment]
closing v1 issues...
