### ISSUE TITLE
Please make this function public

### ISSUE THREAD

**Issue by franzwilhelm** [SYNQfm/SYNQ-Golang#37]
https://github.com/SYNQfm/SYNQ-Golang/blob/8fa06e629c9b71245b06fad53c046aa73fac63aa/synq/multipart_upload.go#L197

**Comment by halvardos** [comment]
Sure, I'll get one of the go proficient devs to get that done asap :)

**Comment by halvardos** [comment]
@franzwilhelm this is now fixed in #38
