### ISSUE TITLE
add Golang documentation to synq.fm

### ISSUE THREAD

**Issue by batmany13** [SYNQfm/SYNQ-Golang#7]
we need to add it to synq.fm/docs once we have the various functions added

**Comment by franzwilhelm** [comment]
Yes please!

**Comment by batmany13** [comment]
@franzwilhelm Thanks for your feedback, any particular areas you'd like more clarity on?  

We tried to cover some very basics in our [README.md](https://github.com/SYNQfm/SYNQ-Golang).  Also, if you check out our [cli](https://github.com/SYNQfm/SYNQ-Golang/blob/master/cli/main.go) file, you can see how we use each API call.

But, it will be great to include additional samples that you'll find useful!
